function menuPage() {
    const mainMenu = document.createElement('div');
    mainMenu.classList.add('mainMenu');
    content.appendChild(mainMenu);
    const container = document.createElement('div');
    container.classList.add('container');
    mainMenu.appendChild(container);
    makeSparkle();
    const whiteContainer = document.createElement('div');
    whiteContainer.classList.add('white-container');
    container.appendChild(whiteContainer);
    makeSparkle();
    makeSparkle();
    makeSparkle();
    const tagName = document.createElement('div');
    tagName.classList.add('tag-name-menu');
    whiteContainer.appendChild(tagName);
    const containerCard = document.createElement('div');
    containerCard.classList.add('con');
    whiteContainer.appendChild(containerCard);
    const shrimp = document.createElement('div');
    shrimp.classList.add('shrimp-card');
    containerCard.appendChild(shrimp);
    const soup = document.createElement('div');
    soup.classList.add('soup');
    containerCard.appendChild(soup);
    const egg = document.createElement('div');
    egg.classList.add('egg');
    containerCard.appendChild(egg);
    const containerCard2 = document.createElement('div');
    containerCard2.classList.add('contain');
    whiteContainer.appendChild(containerCard2);
    const tofu = document.createElement('div');
    tofu.classList.add('tofu');
    containerCard2.appendChild(tofu);
    const Cms = document.createElement('div');
    Cms.classList.add('cms');
    containerCard2.appendChild(Cms);
    const paimon = document.createElement('div');
    paimon.classList.add('paimon');
    mainMenu.appendChild(paimon);
    const vector = document.createElement('div');
    vector.classList.add('vector');
    mainMenu.appendChild(vector);

    function makeSparkle() {
        const sparkle = document.createElement('div');
        sparkle.classList.add('sparkle');
        container.appendChild(sparkle);
    };
};

export default menuPage;